config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  get 'test', to: 'test#index'

  scope module: :sessions do
    get 'sign_in', action: :new
    post 'sign_in', action: :create
    get 'sign_out', action: :destroy
  end

  scope module: :registrations do
    get 'sign_up', action: :new
    post 'sign_up', action: :create
  end

  resources :users, only: :show
  resource :me, only: :show

  resources :categories, shallow: true, only: %i[index show] do
    resources :topics, except: :index do
      resources :posts, except: :index
    end
  end

  namespace :admin do
    root to: 'dashboards#index'

    resources :dashboards, only: :index
  end

  resources :languages, only: :index
end

app/models/topic.rb
class Topic < ApplicationRecord
  include SoftDeletable

  delegate :score, to: :first_post

  enum status: { opening: 0, locked: 5 }

  # TODO: optimize counter cache
  belongs_to :category, counter_cache: true
  belongs_to :creator, class_name: 'User'
  belongs_to :first_post, class_name: 'Post'

  has_one :last_post, -> { visible.order(created_at: :desc) },
    class_name: 'Post'

  has_many :posts

  validates :name, presence: true
  validates :status, presence: true, on: :update

  accepts_nested_attributes_for :first_post

  before_create :set_inital_status

  private

  def set_inital_status
    self.status ||= :opening
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
    @first_post = Post.with_attached_images.find(@topic.first_post.id)
    @posts = @topic.posts.with_attached_images.includes(:creator, :category)
      .order(created_at: :asc)
      .page(params[:page])
  end

  def new
    @category = Category.find(params[:category_id])
    @topic = @category.topics.build
    authorize @topic
    @topic.build_first_post
  end

  def create
    @category = Category.find(params[:category_id])
    @topic = @category.topics.build(create_topic_params)
    authorize @topic
    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render :edit
    end
  end

  private

  def create_topic_params
    first_post_params = params.require(:topic).require(:first_post_attributes)
      .permit(:content, images: [])
      .merge(category: @category, creator: current_user)
      .permit!

    params.require(:topic).permit(:name)
      .merge(creator: current_user, first_post_attributes: first_post_params)
      .permit!
  end

  def topic_params
    permitted_params = [first_post_attributes: [:id, :content, images: []]]
    permitted_params.push(:name) if policy(@topic.category).manage?
    params.require(:topic).permit(permitted_params)
  end
end

app/views/topics/_first_post.slim
.row.post-list-item
  .col.s12
    .row.post-context
      .col.s10
        - if post.deleted?
          span.new.badge.red[
            data-badge-caption=t('activerecord.attributes.deletable.deleted')
          ]

        = post.created_at
      .col.s2.right-align.post-counter
        = t('views.topics.show.posts.original_post')
    - if policy(post).show?
      .row.post-body
        .col.s2
          .post-creator-container
            .post-creator-avatar
              img.image src=asset_path('default_avatar.png')
            .post-creator-info
              .truncate
                =< link_to post.creator.username, user_path(post.creator)
              .truncate.post-creator-role
                = translate_enum(post.creator, :role)

        .col.s10
          .post-content-wrapper
            .post-content
              p.paragraph-content = post.content

              - if post.images.any?
                .post-images-container
                  .post-image-list
                    - post.images.map do |image|
                      .post-image-item
                        .truncate.post-image-caption = image.blob.filename
                        = image_tag image, class: 'image materialboxed',
                          data: { caption: attachment_caption(image) }
            .post-utilities
              .voting-container
                span.score
                  = t('views.topics.show.posts.vote', count: post.score)
                = link_if_signed_in '#!', class: 'vote upvote' do
                  i.fas.fa-caret-up
                  span.vote-desc
                    = t('views.topics.show.posts.upvote')
                = link_if_signed_in '#!', class: 'vote downvote' do
                  i.fas.fa-caret-down
                  span.vote-desc
                    = t('views.topics.show.posts.downvote')

              .actions-container
                - if policy(topic).edit?
                  = link_to edit_topic_path(topic), class: 'edit' do
                    i.fas.fa-pencil-alt
                    = t('views.topics.show.edit')

    - else
      div = t('views.topics.show.posts.deleted.message')

    .post-divider

app/views/topics/_form.slim
.row
  .input-field.col.s12
    = t('views.topics.form.post_to_html', category: topic.category.name)
.card
  .card-content
    = yield if block_given?

    = f.fields_for :first_post do |post_f|
      .row
        .input-field.col.s12
          = post_f.text_area :content,
            class: classnames('materialize-textarea input-with-counter', invalid: topic.errors[:'first_post.content'].present?),
            placeholder: t('views.topics.form.placeholder.content'),
            data: { length: Post::CONTENT_MAXIMUM_LENGTH }
          = post_f.label :content, class: 'required'
          = error_message_for(topic, :'first_post.content')

        .file-field.input-field.col.s12
          .btn
            span = t('views.topics.form.attach')
            = post_f.file_field :images, multiple: true
          .file-path-wrapper
            = text_field_tag :path, nil,
              placeholder: t('views.topics.form.placeholder.images'),
              class: classnames('file-path', invalid: topic.errors[:'first_post.images'].present?)
            = error_message_for(topic, :'first_post.images')

    .right-align
      = link_to category_path(topic.category),
        class: 'btn waves-light waves-effect red mr' do
        i.material-icons.left not_interested
        = t('views.topics.form.cancel')

      = f.button nil, type: :submit, class: 'btn waves-light waves-effect' do
        i.material-icons.left send
        = submit_text

app/views/topics/_post.slim
.row.post-list-item
  .col.s12
    .row.post-context
      .col.s10
        - if post.deleted?
          span.new.badge.red[
            data-badge-caption=t('activerecord.attributes.deletable.deleted')
          ]

        = post.created_at
      .col.s2.right-align.post-counter
        | ##{start_index + post_counter}
    - if policy(post).show?
      .row.post-body
        .col.s2
          .post-creator-container
            .post-creator-avatar
              img.image src=asset_path('default_avatar.png')
            .post-creator-info
              .truncate
                =< link_to post.creator.username, user_path(post.creator)
              .truncate.post-creator-role
                = translate_enum(post.creator, :role)

        .col.s10
          .post-content-wrapper
            .post-content
              p.paragraph-content = post.content

              - if post.images.any?
                .post-images-container
                  .post-image-list
                    - post.images.map do |image|
                      .post-image-item
                        .truncate.post-image-caption = image.blob.filename
                        = image_tag image, class: 'image materialboxed',
                          data: { caption: attachment_caption(image) }
            .post-utilities
              .voting-container
                span.score
                  = t('views.topics.show.posts.vote', count: post.score)
                = link_if_signed_in '#!', class: 'vote upvote' do
                  i.fas.fa-caret-up
                  span.vote-desc
                    = t('views.topics.show.posts.upvote')
                = link_if_signed_in '#!', class: 'vote downvote' do
                  i.fas.fa-caret-down
                  span.vote-desc
                    = t('views.topics.show.posts.downvote')

              .actions-container
                - if policy(post).edit?
                  = link_to edit_post_path(post), class: 'edit' do
                    i.fas.fa-pencil-alt
                    = t('views.topics.show.posts.edit')

                - if policy(post).destroy?
                  = link_to post_path(post), class: 'delete', method: :delete do
                    i.fas.fa-trash-alt
                    = t('views.topics.show.posts.delete')

    - else
      div = t('views.topics.show.posts.deleted.message')

    .post-divider

app/views/topics/edit.slim
= breadcrumbs_for \
  Hash[path: root_path, title: t('views.breadcrumbs.categories')],
  Hash[path: category_path(@topic.category), title: @topic.category.name],
  Hash[path: topic_path(@topic), title: @topic.name],
  Hash[title: t('views.breadcrumbs.topics.edit')]

= content_for :title
  = t('views.topics.edit.title', topic: @topic.name)

= form_with model: @topic, url: topic_path(@topic), method: :put, class: 'topic-form', local: true do |f|
  = render 'topics/form', f: f, topic: @topic, submit_text: t('views.topics.edit.submit') do
    - if policy(@topic.category).manage?
      .row
        .input-field.col.s12
          = f.text_field :name, autofocus: true,
            placeholder: t('views.topics.form.placeholder.name'),
            class: classnames(invalid: @topic.errors[:name].present?)
          = f.label :name, class: 'required'
          = error_message_for(@topic, :name)

app/views/topics/new.slim
= breadcrumbs_for \
  Hash[path: root_path, title: t('views.breadcrumbs.categories')],
  Hash[path: category_path(@category), title: @category.name],
  Hash[title: t('views.breadcrumbs.topics.new')]

= content_for :title do
  = t('views.topics.new.title')

.new-topic-screen
  = form_with model: @topic, url: category_topics_path(@category),
    method: :post, local: true do |f|
    = render 'topics/form', f: f, topic: @topic, submit_text: t('views.topics.new.submit') do
      .row
        .input-field.col.s12
          = f.text_field :name, autofocus: true,
            placeholder: t('views.topics.form.placeholder.name'),
            class: classnames(invalid: @topic.errors[:name].present?)
          = f.label :name, class: 'required'
          = error_message_for(@topic, :name)

app/views/topics/show.slim
= breadcrumbs_for \
  Hash[path: root_path, title: t('views.breadcrumbs.categories')],
  Hash[path: category_path(@topic.category), title: @topic.category.name],
  Hash[title: @topic.name]

= content_for :title do
  = @topic.name

.topic-screen
  .row.valign-wrapper.topic-header
    .col.s3
      = button_if_signed_in new_topic_post_path(@topic) do
        i.material-icons.left create
        = t('views.topics.show.new_post')

    .col.s9 = paginate @posts

  .card.post-list-container.row-list
    = render 'topics/first_post', post: @first_post, topic: @topic

    = render partial: 'topics/post', collection: @posts, as: :post,
      locals: { start_index: start_index_of(@posts) }

  .row.valign-wrapper.topic-footer
    .col.s3
      = button_if_signed_in new_topic_post_path(@topic) do
        i.material-icons.left create
        = t('views.topics.show.new_post')

    .col.s9 = paginate @posts