config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  get 'test', to: 'test#index'

  scope module: :sessions do
    get 'sign_in', action: :new
    post 'sign_in', action: :create
    get 'sign_out', action: :destroy
  end

  scope module: :registrations do
    get 'sign_up', action: :new
    post 'sign_up', action: :create
  end

  resources :users, only: :show
  resource :me, only: :show

  resources :categories, shallow: true, only: %i[index show] do
    resources :topics, except: :index do
      resources :posts, except: :index
    end
  end

  namespace :admin do
    root to: 'dashboards#index'

    resources :dashboards, only: :index
  end

  resources :languages, only: :index
end

app/models/post.rb
class Post < ApplicationRecord
  CONTENT_MAXIMUM_LENGTH = 500

  include SoftDeletable

  belongs_to :creator, class_name: 'User'
  # TODO: optimize counter cache
  belongs_to :topic, optional: true, counter_cache: true
  belongs_to :category, counter_cache: true

  has_many :votings
  has_many_attached :images

  has_many :voters, through: :votings

  validates :content,
    presence: true,
    length: { maximum: CONTENT_MAXIMUM_LENGTH }
  validate :validate_images_format, if: -> { images.attached? }
  validate :validate_images_size, if: -> { images.attached? }
  validate :validate_images_count, if: -> { images.attached? }

  scope :without_first_posts, -> { where.not(topic: nil) }

  def first_post?
    topic.nil?
  end

  private

  def validate_images_format
    return if images
      .detect { |image| !image.blob.content_type.start_with?('image/') }
      .nil?

    errors.add(:images, :format)
  end

  def validate_images_size
    return if images.detect { |image| image.blob.byte_size > 1_000_000 }.nil?

    errors.add(:images, :size)
  end

  def validate_images_count
    return if images.length < 5

    errors.add(:images, :too_many)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(category: @topic.category)
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(create_post_params)
    authorize @post
    if @post.save
      redirect_to @topic
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post.update(post_params)
      redirect_to @post.topic
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.soft_destroy
    redirect_back fallback_location: root_path
  end

  private

  def create_post_params
    post_params.merge(creator: current_user, category: @topic.category).permit!
  end

  def post_params
    params.require(:post).permit(:content, images: [])
  end
end

app/views/posts/_form.slim
.row
  .input-field.col.s12
    = t('views.posts.form.reply_to_html', topic: post.topic.name)
.card
  .card-content
    .row
      .input-field.col.s12
        = f.text_area :content,
          class: classnames('materialize-textarea input-with-counter', invalid: post.errors[:content].present?),
          placeholder: t('views.posts.form.placeholder.content'),
          data: { length: Post::CONTENT_MAXIMUM_LENGTH }
        = f.label :content, class: 'required'
        = error_message_for(post, :content)

      .file-field.input-field.col.s12
        .btn
          span = t('views.posts.form.attach')
          = f.file_field :images, multiple: true
        .file-path-wrapper
          = text_field_tag :path, nil,
            placeholder: t('views.posts.form.placeholder.images'),
            class: classnames('file-path', invalid: post.errors[:images].present?)
          = error_message_for(post, :images)

    .right-align
      = link_to topic_path(post.topic),
        class: 'btn waves-light waves-effect red mr' do
        i.material-icons.left not_interested
        = t('views.posts.form.cancel')

      = f.button nil, type: :submit, class: 'btn waves-light waves-effect' do
        i.material-icons.left send
        = t('views.posts.form.submit')

app/views/posts/edit.slim
= breadcrumbs_for \
  Hash[path: root_path, title: t('views.breadcrumbs.categories')],
  Hash[path: category_path(@post.category), title: @post.category.name],
  Hash[path: topic_path(@post.topic), title: @post.topic.name],
  Hash[title: t('views.breadcrumbs.posts.edit')]

= content_for :title do
  = t('views.posts.edit.title', topic: @post.topic.name)

.edit-post-screen
  = form_with model: @post, url: post_path(@post), local: true, method: :put, class: 'post-form' do |f|
    = render 'posts/form', f: f, post: @post

app/views/posts/new.slim
= breadcrumbs_for \
  Hash[path: root_path, title: t('views.breadcrumbs.categories')],
  Hash[path: category_path(@topic.category), title: @topic.category.name],
  Hash[path: topic_path(@topic), title: @topic.name],
  Hash[title: t('views.breadcrumbs.posts.new')]

= content_for :title do
  = t('views.posts.new.title', topic: @topic.name)

.new-post-screen
  = form_with model: @post, url: topic_posts_path(@post.topic), local: true, method: :post, class: 'post-form' do |f|
    = render 'posts/form', f: f, post: @post