config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  get 'test', to: 'test#index'

  scope module: :sessions do
    get 'sign_in', action: :new
    post 'sign_in', action: :create
    get 'sign_out', action: :destroy
  end

  scope module: :registrations do
    get 'sign_up', action: :new
    post 'sign_up', action: :create
  end

  resources :users, only: :show
  resource :me, only: :show

  resources :categories, shallow: true, only: %i[index show] do
    resources :topics, except: :index do
      resources :posts, except: :index
    end
  end

  namespace :admin do
    root to: 'dashboards#index'

    resources :dashboards, only: :index
  end

  resources :languages, only: :index
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_managements
  has_many :category_bannings
  has_many :topics
  has_many :posts

  has_many :managers, through: :category_managements
  has_many :banned_users, through: :category_bannings, source: :user

  has_one :last_topic, -> { visible.order(created_at: :desc) },
    class_name: 'Topic'

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.includes(last_topic: :creator).order(id: :asc)
  end

  def show
    @category = Category.find(params[:id])
    authorize @category
    @topics = @category.topics
      .includes(:creator, :first_post, last_post: :creator)
      .order(created_at: :desc)
      .page(params[:page])
  end
end

app/views/categories/_category.slim
.category-list-item.row
  .col.s6
    = link_to category_path(category) do
      i.fas.fa-comments.category-icon
      span.category-name = category.name
  .col.s1.center-align.topics-count
    = category.topics.size
  .col.s1.center-align.posts-count
    = category.posts.size
  .col.s4
    - if category.last_topic
      .truncate
        = link_to category.last_topic.name, topic_path(category.last_topic)
      .row.topic-metadata
        .col.s8
          .truncate
            span.topic-started-by
              | #{t('views.categories.index.last_topic.started_by')}:
            =< link_to category.last_topic.creator.username,
              user_path(category.last_topic.creator),
              class: 'topic-creator-name'
        .col.s4
          .truncate.right-align = time_ago_in_words(category.last_topic.created_at)
    - else
      .truncate = t('views.categories.index.last_topic.blank')

  .category-divider

app/views/categories/_topic.slim
- if policy(topic).show?
  .row.topic-list-item
    .col.s7
      .row.valign-wrapper
        .col.s1
          .voting-container
            .vote
              i.fas.fa-caret-up.vote-up
              i.fas.fa-caret-down.vote-down
            .score
              = topic.score
        .col.s11
          .truncate.topic-name-with-status
            - if topic.deleted?
              span.new.badge.red[
                data-badge-caption=t('activerecord.attributes.deletable.deleted')
              ]

            - if topic.locked?
              span.new.badge.blue-grey data-badge-caption=translate_enum(topic, :status)

            = link_to topic.name, topic_path(topic), class: 'topic-name'
          .truncate.topic-metadata
            span.topic-started-by
              = t('views.categories.show.topics.started_by')
              | :
            =< link_to topic.creator.username, user_path(topic.creator),
              class: 'topic-creator-name'
    .col.s1.center-align.posts-count
      = topic.posts.size
    .col.s4
      - if topic.last_post.present?
        .truncate.last-post-content
          = topic.last_post.content
        .row.post-metadata
          .col.s8
            .truncate
              span.post-posted-by
                = t('views.categories.show.topics.last_post.posted_by')
                | :
              =< link_to topic.last_post.creator.username, user_path(topic.last_post.creator),
                class: 'post-creator-name'

          .col.s4
            .truncate.right-align = time_ago_in_words(topic.last_post.created_at)
      - else
        .truncate = t('views.categories.show.topics.last_post.empty')

    .post-divider
- else
  .row.topic-list-item.valign-wrapper
    .col.s7
      .row.valign-wrapper
        .col.s1
          .voting-container
            .vote
              i.fas.fa-caret-up.vote-up
              i.fas.fa-caret-down.vote-down
            .score
              = t('views.categories.show.topics.deleted.votes_count')
        .col.s11
          .truncate.topic-metadata
            span.topic-started-by
              = t('views.categories.show.topics.started_by')
              | :
            =< link_to topic.creator.username, user_path(topic.creator),
              class: 'topic-creator-name'
    .col.s1.center-align
      = t('views.categories.show.topics.deleted.posts_count')
    .col.s4
      = t('views.categories.show.topics.deleted.message')

    .post-divider

app/views/categories/index.slim
= breadcrumbs_for \
  Hash[title: t('views.breadcrumbs.categories')]

= content_for :title do
  = t('views.categories.index.title')

.categories-screen
  .category-list-container.card
    .category-list-header.row-list-header
      .row
        .col.s6
          = t('views.categories.index.row_headers.name')
        .col.s1.center-align
          = t('views.categories.index.row_headers.topics_count')
        .col.s1.center-align
          = t('views.categories.index.row_headers.posts_count')
        .col.s4
          = t('views.categories.index.row_headers.last_topic')
    .category-list.row-list
      = render(@categories) || t('views.categories.index.empty')

app/views/categories/show.slim
= breadcrumbs_for \
  Hash[path: root_path, title: t('views.breadcrumbs.categories')],
  Hash[title: @category.name]

= content_for :title
  = @category.name

.category-screen
  .row.valign-wrapper.category-header
    .col.s3
      = button_if_signed_in new_category_topic_path(@category) do
        i.material-icons.left add
        = t('views.categories.show.new_topic')

    .col.s9 = paginate @topics

  .topic-list-container.card
    .topic-list-header.row-list-header
      .row
        .col.s7
          = t('views.categories.show.row_headers.name')
        .col.s1.center-align
          = t('views.categories.show.row_headers.posts_count')
        .col.s4
          = t('views.categories.show.row_headers.last_post')
    .topic-list.row-list
      = render(partial: 'categories/topic', collection: @topics) || t('views.categories.show.topics.empty')

  = paginate @topics