config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  get 'test', to: 'test#index'

  scope module: :sessions do
    get 'sign_in', action: :new
    post 'sign_in', action: :create
    get 'sign_out', action: :destroy
  end

  scope module: :registrations do
    get 'sign_up', action: :new
    post 'sign_up', action: :create
  end

  resources :users, only: :show
  resource :me, only: :show

  resources :categories, shallow: true, only: %i[index show] do
    resources :topics, except: :index do
      resources :posts, except: :index
    end
  end

  namespace :admin do
    root to: 'dashboards#index'

    resources :dashboards, only: :index
  end

  resources :languages, only: :index
end

app/views/layouts/_breadcrumbs.slim
= content_for :breadcrumbs
  nav.breadcrumbs
    .bs-container
      .nav-wrapper
        .col.s12.truncate
          - links.map do |link|
            - if link[:path]
              a.breadcrumb href=link[:path] alt=link[:title] = link[:title]
            - else
              span.breadcrumb = link[:title]

app/views/layouts/_footer.slim
footer.page-footer
  .bs-container
    .row
      .col.l6.s12
        h5.white-text = t('views.footer.team')
        p.grey-text.text-lighten-4 20cm
      .col.l4.offset-l2.s12
        h5.white-text = t('views.footer.links')
        ul
          li
            a.grey-text.text-lighten-3 href="#!" 20cm
          li
            a.grey-text.text-lighten-3 href="#!" 20cm
          li
            a.grey-text.text-lighten-3 href="#!" 20cm
          li
            a.grey-text.text-lighten-3 href="#!" 20cm
  .footer-copyright
    .bs-container
      = "#{t('views.footer.copyright')} #{t('views.footer.team')}"

app/views/layouts/_head.slim
title
  => yield :title
  | | CLvOZ

meta name="viewport" content="width=device-width, initial-scale=1.0"
= csrf_meta_tags
= csp_meta_tag

link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
= stylesheet_link_tag    'application', media: 'all'
= javascript_include_tag 'application'

app/views/layouts/_navbar.slim
.navbar-fixed
  - if signed_in?
    ul#userSettingsDropdown.dropdown-content
      li
        a href="#!" = t('views.navbar.dropdown.settings')
      li
        = link_to t('views.navbar.dropdown.sign_out'), sign_out_path

  nav.navbar
    .bs-container
      .nav-wrapper
        = link_to t('views.navbar.home'), root_path, class: 'brand-logo'

        - if signed_in?
          ul#userNavUtils.right.hide-on-med-and-down
            - if policy(:application).manage?
              li class=classnames(active: current_page?(admin_dashboards_path))
                a href=admin_dashboards_path
                  = t('views.navbar.dashboard')
            li.nav-avatar
              a href="#!"
                img.image src=asset_path('default_avatar.png')
            li
              a.dropdown-trigger href="#!" data-target="userSettingsDropdown"
                i.material-icons.right
                  | arrow_drop_down
        - else
          ul#guestNavUtils.right.hide-on-med-and-down
            li
              = link_to t('views.navbar.guest.sign_in'), sign_in_path
            li
              = link_to t('views.navbar.guest.sign_up'), sign_up_path

        ul#languageSwitcher.right.hide-on-med-and-down
          li
            a.dropdown-trigger.current-language href="#!" data-target="languageDropdown"
              i.fas.fa-globe
              = t(I18n.locale, scope: 'views.languages')
            ul#languageDropdown.dropdown-content
              - selectable_locales.each do |locale|
                li
                  = link_to t(locale, scope: 'views.languages'),
                    languages_path(locale: locale)

app/views/layouts/_sidenav.slim
ul.card.collection.with-header.admin-sidenav
  li.collection-header
    h6 = t('views.admin.sidenav.title')

  li.collection-item.avatar.valign-wrapper class=classnames(active: current_page?(admin_dashboards_path))
    i.material-icons dashboard
    span.title = t('views.admin.sidenav.dashboard')

  li.collection-item.avatar.valign-wrapper
    i.material-icons dashboard
    span.title = t('views.admin.sidenav.placeholder')

  li.collection-item.avatar.valign-wrapper
    i.material-icons dashboard
    span.title = t('views.admin.sidenav.placeholder')

  li.collection-item.avatar.valign-wrapper
    i.material-icons dashboard
    span.title = t('views.admin.sidenav.placeholder')

  li.collection-item.avatar.valign-wrapper
    i.material-icons dashboard
    span.title = t('views.admin.sidenav.placeholder')

app/views/layouts/admin.slim
doctype html
html lang=I18n.locale
  head
    = render 'layouts/head'

  body.animated.fadeIn
    = render 'layouts/navbar'
    = yield :breadcrumbs

    .row
      .col.s12
        #appContainer.bs-container
          .row
            .col.s3
              = render 'layouts/sidenav'
            .col.s9
              = yield

    = render 'layouts/footer'

app/views/layouts/application.slim
doctype html
html lang=I18n.locale
  head
    = render 'layouts/head'

  body
    = render 'layouts/navbar'
    = yield :breadcrumbs

    .row
      .col.s12
        #appContainer.bs-container
          = yield

    = render 'layouts/footer'

app/views/layouts/auth.slim
doctype html
html lang=I18n.locale
  head
    = render 'layouts/head'

  body.animated.fadeIn
    = yield